### ISSUE TITLE
[Desarrollo] - Definir un estándar para escribir componentes React

### ISSUE THREAD

**Issue by molavec** [molavec/kriya#1]
## User Story

**Como un**
Desarrollador

**Requiero **
un estándar de como escribir un componente en **Typescript**, es decir, saber que Type hay acompañar.

**Lo que se debe entregar**
un componente que siga un estándar justificadon ese estandar a partir de una documentación, que puede ser **un artículo o documentación ofical que justifique esto**.

Ejemplo:

```javascript

import {{¿QUÉ TIPO DE IMPORT DEBERÍA IR ACÁ?}}

const PoweredBy: {{¿QUÉ TIPO DEBERÍA IR AQUÍ?}}= () => (
  <div className="powered-by">
  </div>
);

export default PoweredBy;

```

**Comment by molavec** [comment]
* https://www.pluralsight.com/guides/how-to-statically-type-react-components-with-typescript
* https://www.pluralsight.com/guides/composing-react-components-with-typescript

**Comment by Redhotnacho** [comment]
Definimos utilizar para este proyecto la notación del tipo `FunctionComponent`

```javascript
const ReactFCComponent: React.FunctionComponent<{title:string}> = ({children, title}) => {
        return <div title={title}>{children}</div>
    }
```

**Comment by Redhotnacho** [comment]
`FunctionComponent` es una interfaz que define un `function signature`. Alternativamente, se puede usar `FC` que es el `type alias` de `FunctionComponent`.

**More info:** 

* https://github.com/typescript-cheatsheets/react/issues/190
* https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types
* https://developer.mozilla.org/en-US/docs/Glossary/Signature/Function
